/// A follow-up task as shown on the worker's task list (FR-07.3), sourced
/// from the `actions` generated by a voice visit (type == "followup").
class FollowupTask {
  final String actionId;
  final String content;
  final String riskLevel; // drives sort order: HIGH (48h) -> MEDIUM (7d) -> LOW (30d)
  final DateTime? dueAt;
  final String status; // pending | done

  FollowupTask({
    required this.actionId,
    required this.content,
    required this.riskLevel,
    required this.dueAt,
    required this.status,
  });

  static const Map<String, int> _riskOrder = {'HIGH': 0, 'MEDIUM': 1, 'LOW': 2};

  int get sortWeight => _riskOrder[riskLevel] ?? 3;
}
