"""Copy a local SQLite database into a deployed Postgres one.

    cd backend
    export TARGET_DATABASE_URL="<External Database URL from Render>"
    export ENCRYPTION_KEY="<the key that is set on Render>"
    PYTHONPATH=. .venv/bin/python scripts/migrate_sqlite_to_postgres.py --dry-run
    PYTHONPATH=. .venv/bin/python scripts/migrate_sqlite_to_postgres.py --apply

Why this exists
---------------
scripts/seed_synthetic_data.py invents new fake rows every time it runs, so
running it on a deployed database does not reproduce the database you have
locally -- it produces a different one with different names. If what you
want on the server is the data you have been demoing against, that is a
copy, not a re-seed. This is the copy.

What it does to the target
--------------------------
Deletes every row in the eight application tables, then inserts yours. It
is a replacement, not a merge: merging two sets of rows that were both
generated by the same script gives you two unrelated ASHAs with similar
names and no way to tell which is which. --dry-run reports what it would
do and writes nothing; --apply is required to actually write.

The encryption key
------------------
Patient names/phones and visit transcripts are encrypted at rest. Rows are
read through the ORM, so they are decrypted on the way out and re-encrypted
on the way in -- which means ENCRYPTION_KEY here must be the key the TARGET
uses, or the server will read your rows as gibberish. The script refuses to
run if the local .env key and the target key disagree, because that mistake
is silent: the copy "succeeds" and every name comes out corrupted.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from sqlalchemy import create_engine, inspect
from sqlalchemy.orm import sessionmaker

# Insert order. Parents before children -- a patient cannot reference a
# worker that is not there yet. Deletion walks this list backwards.
from app.db.models.action import Action
from app.db.models.audit_log import AuditLog
from app.db.models.hmis_report import HmisReport
from app.db.models.patient import Patient
from app.db.models.risk_flag import RiskFlag
from app.db.models.sync_queue import SyncQueueEntry
from app.db.models.visit import Visit
from app.db.models.worker import Worker

ORDER = [Worker, AuditLog, SyncQueueEntry, Patient, HmisReport, Visit, Action, RiskFlag]

SOURCE = Path(__file__).resolve().parent.parent / "sevakai_dev.db"


def _row_to_dict(obj) -> dict:
    """Plain column values, no relationships.

    Reading through the ORM means EncryptedString has already decrypted
    the protected columns, so what comes back here is plaintext and gets
    re-encrypted on insert with the target's key.
    """
    return {c.key: getattr(obj, c.key) for c in inspect(obj).mapper.column_attrs}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="actually write (default is a dry run)")
    parser.add_argument("--dry-run", action="store_true", help="report only; the default")
    args = parser.parse_args()

    target_url = os.environ.get("TARGET_DATABASE_URL", "").strip()
    if not target_url:
        print("TARGET_DATABASE_URL is not set. Paste Render's External Database URL into it.")
        return 1
    if target_url.startswith("sqlite"):
        print("TARGET_DATABASE_URL points at SQLite. That is the source, not the target.")
        return 1
    if not SOURCE.exists():
        print(f"No source database at {SOURCE}")
        return 1

    # Guard the silent-corruption case described in the docstring.
    env_key = ""
    env_file = SOURCE.parent / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            if line.startswith("ENCRYPTION_KEY="):
                env_key = line.split("=", 1)[1].split("#")[0].strip()
    running_key = os.environ.get("ENCRYPTION_KEY", "").strip()
    if env_key and running_key and env_key != running_key:
        print("ENCRYPTION_KEY does not match the one in backend/.env.")
        print("The source rows were encrypted with the .env key; writing them under a")
        print("different key would succeed and produce unreadable names. Refusing.")
        return 1

    # Two engines rather than the app's global one, because this is the one
    # place in the project that legitimately talks to two databases at once.
    src = sessionmaker(bind=create_engine(f"sqlite:///{SOURCE}", connect_args={"check_same_thread": False}))()
    if target_url.startswith("postgres://"):
        target_url = "postgresql://" + target_url[len("postgres://"):]
    if target_url.startswith("postgresql://"):
        target_url = "postgresql+psycopg2://" + target_url[len("postgresql://"):]
    dst_engine = create_engine(target_url, pool_pre_ping=True)
    dst = sessionmaker(bind=dst_engine)()

    try:
        print(f"source : {SOURCE}")
        print(f"target : {target_url.split('@')[-1]}\n")
        print(f"{'table':16} {'source':>8} {'target now':>11}")
        payload: dict = {}
        for model in ORDER:
            rows = src.query(model).all()
            payload[model] = rows
            here = dst.query(model).count()
            print(f"  {model.__tablename__:16} {len(rows):6} {here:11}")

        if not args.apply:
            print("\nDry run -- nothing written. Re-run with --apply to replace the target.")
            return 0

        print("\nDeleting target rows (children first)…")
        for model in reversed(ORDER):
            n = dst.query(model).delete()
            print(f"  {model.__tablename__:16} -{n}")
        dst.commit()

        print("\nInserting…")
        for model in ORDER:
            rows = payload[model]
            for obj in rows:
                dst.add(model(**_row_to_dict(obj)))
            dst.flush()
            print(f"  {model.__tablename__:16} +{len(rows)}")
        dst.commit()

        print("\nVerifying…")
        ok = True
        for model in ORDER:
            want, got = len(payload[model]), dst.query(model).count()
            flag = "" if want == got else "   MISMATCH"
            ok &= want == got
            print(f"  {model.__tablename__:16} {got:6} / {want}{flag}")

        # Prove the encrypted columns survived: a name that decrypts to
        # gibberish is the failure this whole script is arranged to avoid,
        # and a row count cannot detect it.
        sample = dst.query(Patient).first()
        if sample is not None:
            print(f"\n  sample patient name reads back as: {sample.name!r}")
        return 0 if ok else 1
    finally:
        src.close()
        dst.close()


if __name__ == "__main__":
    sys.exit(main())
