"""FR-04.1: a HIGH-risk referral letter has to name the patient's actual
PHC, not a hardcoded placeholder, and has to be legible in the language
the visit was recorded in -- not always English.

Before this, every referral letter (from a fresh HIGH visit and from a
supervisor override alike) was addressed to the literal string "Primary
Health Centre" regardless of which sub-centre the patient belonged to,
and was always English regardless of language_code.
"""
import asyncio
import base64

from fastapi.testclient import TestClient

from app.agents.agent3_action_generation import (
    DEFAULT_PHC,
    build_referral_letter,
    generate,
)
from app.db.models.action import Action
from app.db.session import SessionLocal
from app.main import app
from app.schemas.visit import ExtractedFields, RiskDriver
from app.services.identity import phc_name
from app.services.llm_client import MockLLMClient
from app.services.sms_client import MockSmsClient
from app.services.whatsapp_client import MockWhatsAppClient
from scripts.seed_synthetic_data import seed_demo_fixtures

DEMO_TRANSCRIPT = (
    "Meera Patil, 28 saal, 7 mahine ki pregnancy. Aaj BP 140 over 90 tha. "
    "Usne pichle 2 hafte se iron tablets nahi li. Pati bahar gaya hua hai."
)


# ── identity.phc_name ────────────────────────────────────────────────────

def test_phc_name_derives_the_sub_centres_own_phc():
    """SC-PUNE-01 -> "Pune PHC" is not a guess: it is the exact name the
    SRS demo script (section 9) already uses for this sub-centre."""
    assert phc_name("SC-PUNE-01") == "Pune PHC"


def test_phc_name_drops_the_serial_not_just_the_prefix():
    """Two sub-centres in the same area share one PHC in a real
    deployment -- "SC-PUNE-02" must resolve to the same "Pune PHC", not
    invent a second facility per sub-centre."""
    assert phc_name("SC-PUNE-02") == "Pune PHC"


def test_phc_name_falls_back_when_there_is_no_sub_centre():
    assert phc_name(None) == DEFAULT_PHC
    assert phc_name("") == DEFAULT_PHC


# ── build_referral_letter ────────────────────────────────────────────────

def test_referral_letter_default_language_is_hindi_not_english():
    text = build_referral_letter("Pune PHC", "Meera Patil", "BP 140/90", age=28, pregnancy_stage="7 months")
    assert "रेफरल पत्र" in text
    assert "उच्च जोखिम" in text
    assert "Pune PHC" in text
    assert "REFERRAL LETTER" not in text


def test_referral_letter_english_is_byte_identical_to_the_old_template():
    """Regression guard: refactoring the two call sites onto one shared
    template must not change what a plain-English letter looks like."""
    text = build_referral_letter(
        "Primary Health Centre", "Meera Patil", "BP 140/90 -- pre-eclampsia threshold",
        "en", age=28, pregnancy_stage="7 months",
    )
    assert text == (
        "REFERRAL LETTER\n\n"
        "To: Primary Health Centre\n"
        "Patient: Meera Patil, Age 28\n"
        "Pregnancy stage: 7 months\n\n"
        "Reason for referral (HIGH risk): BP 140/90 -- pre-eclampsia threshold\n\n"
        "Please prioritise clinical review at earliest opportunity.\n"
        "-- Generated by SevakAI"
    )


def test_referral_letter_omits_clinical_fields_when_asked():
    """The override path has a reason but no structured extracted fields
    -- show_clinical_fields=False must not print "Age: N/A" as if data
    went missing."""
    text = build_referral_letter("Pune PHC", "Meera Patil", "reason", show_clinical_fields=False)
    assert "आयु" not in text  # "Age" label
    assert "गर्भावस्था" not in text  # "Pregnancy stage" label


def test_unrecognised_language_falls_back_to_english_not_a_guess():
    text = build_referral_letter("Pune PHC", "Meera Patil", "reason", language_code="mr")
    assert "REFERRAL LETTER" in text


# ── generate() wiring ────────────────────────────────────────────────────

def _high_risk_args(**overrides):
    args = dict(
        extracted=ExtractedFields(age=28, pregnancy_stage="7 months"),
        risk_level="HIGH",
        risk_drivers=[RiskDriver(observation="BP 140/90", reason="pre-eclampsia threshold")],
        patient_name="Meera Patil",
        patient_phone="9876543210",
        llm_client=MockLLMClient(),
        whatsapp_client=MockWhatsAppClient(),
        sms_client=MockSmsClient(),
    )
    args.update(overrides)
    return args


def test_generate_resolves_the_caseloads_own_phc():
    actions = asyncio.run(generate(**_high_risk_args(phc_name=phc_name("SC-PUNE-01"))))
    referral = next(a for a in actions if a["type"] == "referral")
    assert "Pune PHC" in referral["content"]
    assert "Primary Health Centre" not in referral["content"]


def test_generate_defaults_to_hindi_language_code():
    actions = asyncio.run(generate(**_high_risk_args()))
    referral = next(a for a in actions if a["type"] == "referral")
    assert "रेफरल पत्र" in referral["content"]


def test_generate_honours_an_explicit_language_code():
    actions = asyncio.run(generate(**_high_risk_args(language_code="en")))
    referral = next(a for a in actions if a["type"] == "referral")
    assert "REFERRAL LETTER" in referral["content"]


# ── end-to-end: a real HIGH voice visit ──────────────────────────────────

def _seed():
    db = SessionLocal()
    try:
        seed_demo_fixtures(db)
    finally:
        db.close()


def test_a_fresh_high_voice_visit_referral_names_the_actual_phc():
    """The wiring, not just the unit function: run_voice_visit -> graph.py
    -> agent3.generate must resolve the demo patient's own PHC end to
    end, with no test touching phc_name or build_referral_letter
    directly."""
    with TestClient(app) as client:
        _seed()
        login = client.post("/api/v1/auth/login", json={"phone": "9999999999", "pin": "1234"})
        asha = login.json()
        headers = {"Authorization": f"Bearer {asha['access_token']}"}
        patients = client.get(f"/api/v1/patients/{asha['worker_id']}", headers=headers)
        meera = next(p for p in patients.json()["patients"] if p["name"] == "Meera Patil")

        audio_b64 = base64.b64encode(DEMO_TRANSCRIPT.encode()).decode()
        resp = client.post(
            "/api/v1/visits/voice",
            headers=headers,
            json={
                "worker_id": asha["worker_id"], "patient_id": meera["id"],
                "audio_base64": audio_b64, "language_code": "hi",
            },
        )
        assert resp.status_code == 200, resp.text
        visit = resp.json()
        assert visit["risk_level"] == "HIGH"

        db = SessionLocal()
        try:
            referral = (
                db.query(Action)
                .filter(Action.visit_id == visit["visit_id"], Action.type == "referral")
                .first()
            )
            assert referral is not None
            assert "Pune PHC" in referral.content
            assert "रेफरल पत्र" in referral.content
        finally:
            db.close()
