"""baseline schema -- the shape the database was already in when migrations arrived.

This project ran on `Base.metadata.create_all()` alone, which creates
missing tables and never alters an existing one. That is correct exactly
once, against an empty database; the first model change after a deploy
left Postgres missing a column and the error arrived at runtime, in
whichever endpoint touched it first. `app/db/session.py::_add_missing_columns`
was the stopgap for that, and it is deliberately additive-only -- it cannot
rename, retype or drop anything.

This revision is the baseline those two were working without.

**On a database that already has these tables, do not run this.** Tell
Alembic it is already here, then migrate forward from now on:

    alembic stamp head

**On an empty database**, this creates everything:

    alembic upgrade head

From here, a model change means `alembic revision --autogenerate -m "..."`,
reading the generated file before applying it. `_add_missing_columns` stays
for now so an existing deployment that has not been stamped still boots,
but new columns belong in a revision, not in that dict.

Revision ID: 405a3a6e07df
Revises: 
Create Date: 2026-09-20

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# EncryptedString is a custom TypeDecorator (app/core/encryption.py), and
# autogenerate renders it by its fully-qualified name -- so every revision
# touching an encrypted column needs this import or it fails at runtime
# with NameError. Imported here rather than rewritten to sa.Text() because
# the type is what tells a future reader the column is ciphertext.
import app.core.encryption


# revision identifiers, used by Alembic.
revision: str = '405a3a6e07df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('support_tickets',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('message', app.core.encryption.EncryptedString(), nullable=False),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_worker_id'), ['worker_id'], unique=False)

    op.create_table('sync_queue',
    sa.Column('queue_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('record_json', app.core.encryption.EncryptedString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('queue_id')
    )
    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_queue_worker_id'), ['worker_id'], unique=False)

    op.create_table('visit_requests',
    sa.Column('request_key', sa.String(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('response_json', app.core.encryption.EncryptedString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('request_key')
    )
    op.create_table('worker_absences',
    sa.Column('absence_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('covering_worker_id', sa.String(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('absence_id')
    )
    with op.batch_alter_table('worker_absences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_absences_covering_worker_id'), ['covering_worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_absences_ends_on'), ['ends_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_absences_starts_on'), ['starts_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_absences_worker_id'), ['worker_id'], unique=False)

    op.create_table('workers',
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('language_pref', sa.String(), nullable=False),
    sa.Column('sub_centre_id', sa.String(), nullable=True),
    sa.Column('district_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('worker_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workers_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_workers_worker_code'), ['worker_code'], unique=True)

    op.create_table('hmis_reports',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    with op.batch_alter_table('hmis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hmis_reports_worker_id'), ['worker_id'], unique=False)

    op.create_table('patients',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('name', app.core.encryption.EncryptedString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('phone', app.core.encryption.EncryptedString(), nullable=True),
    sa.Column('pregnancy_stage', sa.String(), nullable=True),
    sa.Column('rch_number', sa.String(), nullable=True),
    sa.Column('phone_hash', sa.String(), nullable=True),
    sa.Column('village_code', sa.String(), nullable=True),
    sa.Column('sub_centre_id', sa.String(), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('blood_sugar_fasting', sa.Integer(), nullable=True),
    sa.Column('blood_sugar_random', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('closed_reason', app.core.encryption.EncryptedString(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_phone_hash'), ['phone_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_rch_number'), ['rch_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_sub_centre_id'), ['sub_centre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_village_code'), ['village_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_worker_id'), ['worker_id'], unique=False)

    op.create_table('visits',
    sa.Column('visit_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('transcript', app.core.encryption.EncryptedString(), nullable=True),
    sa.Column('structured_json', app.core.encryption.EncryptedString(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.worker_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_worker_id'), ['worker_id'], unique=False)

    op.create_table('actions',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('visit_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', app.core.encryption.EncryptedString(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_visit_id'), ['visit_id'], unique=False)

    op.create_table('risk_flags',
    sa.Column('flag_id', sa.String(), nullable=False),
    sa.Column('visit_id', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('drivers_json', app.core.encryption.EncryptedString(), nullable=True),
    sa.Column('overridden_by', sa.String(), nullable=True),
    sa.Column('override_reason', app.core.encryption.EncryptedString(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('actioned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ),
    sa.PrimaryKeyConstraint('flag_id')
    )
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_flags_visit_id'), ['visit_id'], unique=False)

    op.create_table('risk_resolutions',
    sa.Column('visit_id', sa.String(), nullable=False),
    sa.Column('resolved_by', sa.String(), nullable=False),
    sa.Column('note', app.core.encryption.EncryptedString(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.visit_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_table('notification_outbox',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('payload_json', app.core.encryption.EncryptedString(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.action_id'], ),
    sa.PrimaryKeyConstraint('action_id')
    )
    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_outbox_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_outbox_status'))

    op.drop_table('notification_outbox')
    op.drop_table('risk_resolutions')
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_flags_visit_id'))

    op.drop_table('risk_flags')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_visit_id'))

    op.drop_table('actions')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_worker_id'))
        batch_op.drop_index(batch_op.f('ix_visits_patient_id'))

    op.drop_table('visits')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_worker_id'))
        batch_op.drop_index(batch_op.f('ix_patients_village_code'))
        batch_op.drop_index(batch_op.f('ix_patients_sub_centre_id'))
        batch_op.drop_index(batch_op.f('ix_patients_status'))
        batch_op.drop_index(batch_op.f('ix_patients_rch_number'))
        batch_op.drop_index(batch_op.f('ix_patients_phone_hash'))

    op.drop_table('patients')
    with op.batch_alter_table('hmis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hmis_reports_worker_id'))

    op.drop_table('hmis_reports')
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_worker_code'))
        batch_op.drop_index(batch_op.f('ix_workers_phone'))
        batch_op.drop_index(batch_op.f('ix_workers_district_id'))

    op.drop_table('workers')
    with op.batch_alter_table('worker_absences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_absences_worker_id'))
        batch_op.drop_index(batch_op.f('ix_worker_absences_starts_on'))
        batch_op.drop_index(batch_op.f('ix_worker_absences_ends_on'))
        batch_op.drop_index(batch_op.f('ix_worker_absences_covering_worker_id'))

    op.drop_table('worker_absences')
    op.drop_table('visit_requests')
    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_queue_worker_id'))

    op.drop_table('sync_queue')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_worker_id'))

    op.drop_table('support_tickets')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
