"""correction documents

Revision ID: a68208122710
Revises: 405a3a6e07df
Create Date: 2026-09-24 09:12:22.205228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Needed whenever a revision touches an EncryptedString column.
import app.core.encryption  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'a68208122710'
down_revision: Union[str, Sequence[str], None] = '405a3a6e07df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correction_documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('filename', app.core.encryption.EncryptedString(), nullable=True),
    sa.Column('changed_fields', sa.Text(), nullable=False),
    sa.Column('reason', app.core.encryption.EncryptedString(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('uploaded_by_name', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('correction_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correction_documents_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correction_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correction_documents_patient_id'))

    op.drop_table('correction_documents')
    # ### end Alembic commands ###
