"""Agent 3 -- Action Generation (FR-04): referral letter, WhatsApp draft,
follow-up task with risk-based due date."""
from datetime import datetime, timedelta, timezone

from app.schemas.visit import ExtractedFields, RiskDriver
from app.services.llm_client import LLMClientBase
from app.services.whatsapp_client import WhatsAppClientBase

# FR-04.3: HIGH -> 48h, MEDIUM -> 7d, LOW -> 30d
FOLLOWUP_DAYS = {"HIGH": 2, "MEDIUM": 7, "LOW": 30}
DEFAULT_PHC = "Primary Health Centre"


async def generate(
    extracted: ExtractedFields,
    risk_level: str,
    risk_drivers: list[RiskDriver],
    patient_name: str,
    patient_phone: str | None,
    llm_client: LLMClientBase,
    whatsapp_client: WhatsAppClientBase,
    phc_name: str = DEFAULT_PHC,
) -> list[dict]:
    actions: list[dict] = []
    now = datetime.now(timezone.utc)
    driver_text = "; ".join(f"{d.observation} -- {d.reason}" for d in risk_drivers)

    # FR-04.1: referral letter only for HIGH risk patients.
    if risk_level == "HIGH":
        referral_text = (
            f"REFERRAL LETTER\n\n"
            f"To: {phc_name}\n"
            f"Patient: {patient_name}, Age {extracted.age or 'N/A'}\n"
            f"Pregnancy stage: {extracted.pregnancy_stage or 'N/A'}\n\n"
            f"Reason for referral (HIGH risk): {driver_text}\n\n"
            f"Please prioritise clinical review at earliest opportunity.\n"
            f"-- Generated by SevakAI"
        )
        actions.append({"type": "referral", "content": referral_text, "status": "draft"})

    # FR-04.2: WhatsApp summary draft in local language (template for now --
    # swap to llm_client.complete() for a fluent localized draft once an LLM
    # key is set; template keeps this deterministic for the mock path).
    whatsapp_text = (
        f"Namaste {patient_name} ji, aapke ghar visit ke observations note kar liye gaye hain. "
        f"Risk status: {risk_level}. "
        + ("Kripya jaldi PHC visit karein." if risk_level == "HIGH" else "Apna follow-up visit na bhoolein.")
    )
    wa_result = await whatsapp_client.send_message(patient_phone or "", whatsapp_text)
    actions.append({
        "type": "whatsapp",
        "content": whatsapp_text,
        "status": wa_result.get("status", "draft"),
    })

    # FR-04.3: follow-up task.
    due_days = FOLLOWUP_DAYS.get(risk_level, 30)
    due_at = now + timedelta(days=due_days)
    actions.append({
        "type": "followup",
        "content": f"Follow-up visit for {patient_name} ({risk_level} risk)",
        "status": "pending",
        "due_at": due_at.isoformat(),
    })

    return actions
