"""Agent 3 -- Action Generation (FR-04): referral letter, WhatsApp draft,
follow-up task with risk-based due date."""
import logging
from datetime import datetime, timedelta, timezone

from app.core.config import get_settings
from app.schemas.visit import ExtractedFields, RiskDriver
from app.services.llm_client import LLMClientBase, MockLLMClient
from app.services.sms_client import MockSmsClient, SmsClientBase
from app.services.whatsapp_client import WhatsAppClientBase

# FR-04.3: HIGH -> 48h, MEDIUM -> 7d, LOW -> 30d
FOLLOWUP_DAYS = {"HIGH": 2, "MEDIUM": 7, "LOW": 30}
DEFAULT_PHC = "Primary Health Centre"

logger = logging.getLogger(__name__)


async def _draft_referral_letter(
    llm_client: LLMClientBase,
    patient_name: str,
    extracted: ExtractedFields,
    phc_name: str,
    driver_text: str,
) -> str:
    """FR-04.1. Deterministic template while LLM_PROVIDER=mock (the default
    -- keeps the demo pipeline offline and reproducible); real LLM-drafted
    prose once LLM_PROVIDER=real. Branches on the client type rather than
    calling complete() unconditionally, because MockLLMClient's own generic
    placeholder text ("[mock LLM response for prompt beginning: ...]") is
    not something a user should ever actually see."""
    deterministic = (
        f"REFERRAL LETTER\n\n"
        f"To: {phc_name}\n"
        f"Patient: {patient_name}, Age {extracted.age or 'N/A'}\n"
        f"Pregnancy stage: {extracted.pregnancy_stage or 'N/A'}\n\n"
        f"Reason for referral (HIGH risk): {driver_text}\n\n"
        f"Please prioritise clinical review at earliest opportunity.\n"
        f"-- Generated by SevakAI"
    )
    if isinstance(llm_client, MockLLMClient):
        return deterministic
    try:
        body = await llm_client.complete(
            "You are drafting a formal referral letter from an ASHA (Accredited Social "
            "Health Activist) community health worker in India to a Primary Health Centre. "
            "Write 4-6 concise, clinically appropriate sentences: identify the patient, "
            "state the specific reasons for referral drawn only from the observations "
            "given, and request prompt review. Do not invent facts not provided. Do not "
            "add a greeting, letterhead, or sign-off -- those are added separately.",
            f"Patient: {patient_name}, Age {extracted.age or 'unknown'}. "
            f"Pregnancy stage: {extracted.pregnancy_stage or 'not specified'}. "
            f"Referring PHC: {phc_name}. "
            f"Risk drivers: {driver_text}.",
        )
    except Exception as exc:  # noqa: BLE001 -- see _attempt: a drafting
        # failure must not lose the visit. Same fallback discipline as
        # extract_with_llm and classify_with_llm.
        logger.warning("referral drafting failed, using deterministic text: %s", exc)
        return deterministic
    return f"REFERRAL LETTER\n\nTo: {phc_name}\n\n{body.strip()}\n\n-- Generated by SevakAI"


async def _draft_whatsapp_message(
    llm_client: LLMClientBase,
    patient_name: str,
    risk_level: str,
    driver_text: str,
) -> str:
    """FR-04.2. Same mock/real split as the referral letter above."""
    deterministic = (
        f"Namaste {patient_name} ji, aapke ghar visit ke observations note kar liye gaye hain. "
        f"Risk status: {risk_level}. "
        + ("Kripya jaldi PHC visit karein." if risk_level == "HIGH" else "Apna follow-up visit na bhoolein.")
    )
    if isinstance(llm_client, MockLLMClient):
        return deterministic
    try:
        return await llm_client.complete(
            "You are an ASHA (Indian community health worker) drafting a short WhatsApp "
            "message in simple, warm Hindi (Devanagari script) to a patient after a home "
            "visit. Use respectful 'aap/ji' forms, avoid medical jargon, and keep it to "
            "2-3 short sentences: acknowledge the visit, mention what was observed in "
            "plain terms, and say what to do next.",
            f"Patient name: {patient_name}. Risk level: {risk_level}. "
            f"Observations: {driver_text or 'routine check, nothing concerning noted'}.",
        )
    except Exception as exc:  # noqa: BLE001 -- see above
        logger.warning("WhatsApp drafting failed, using deterministic text: %s", exc)
        return deterministic


# The three blanks the approved template declares, in her language rather
# than the API's. A patient should not be told her status is "HIGH".
_RISK_WORD = {
    "HIGH": "उच्च जोखिम",
    "MEDIUM": "मध्यम जोखिम",
    "LOW": "सामान्य",
}

_WHEN_WORD = {
    2: "दो दिन के अंदर",
    7: "एक हफ़्ते में",
    30: "एक महीने में",
}


async def _deliver_whatsapp(
    whatsapp_client: WhatsAppClientBase,
    patient_phone: str,
    patient_name: str,
    risk_level: str,
    drafted_text: str,
    due_days: int,
) -> dict:
    """Send the approved template, falling back to the drafted text on any
    provider that has no template concept.

    The fallback is not a workaround for an unapproved template -- it is
    for the mock and Twilio-sandbox providers, where free-form genuinely
    is the right call. On the meta path a refused template surfaces as a
    WhatsAppError with Meta's own reason rather than being papered over,
    because silently sending something else is how you find out at the
    demo that nothing was ever delivered.
    """
    settings = get_settings()
    try:
        return await whatsapp_client.send_template(
            patient_phone,
            settings.whatsapp_template_name,
            [
                patient_name,
                _RISK_WORD.get(risk_level, risk_level),
                _WHEN_WORD.get(due_days, f"{due_days} दिन में"),
            ],
            settings.whatsapp_template_language,
        )
    except NotImplementedError:
        return await whatsapp_client.send_message(patient_phone, drafted_text)


async def _attempt(send, channel: str) -> dict:
    """Run one delivery, turning any failure into a recorded outcome.

    Delivery must never be able to fail a visit. Agent 3 runs *after* the
    transcript, the extracted record and the risk classification already
    exist, and those are the things that matter clinically -- an expired
    WhatsApp token or a Twilio outage was taking the whole request down
    with it, so the ASHA saw no risk level at all for a visit the system
    had already assessed correctly.

    The failure is not swallowed: it lands on the action as status
    "failed" with the provider's own reason, so it is visible in the app
    and the dashboard and can be retried, rather than silently dropped.
    """
    try:
        result = await send()
        return {"status": result.get("status", "sent")}
    except Exception as exc:  # noqa: BLE001 -- deliberately broad; see above
        reason = f"{type(exc).__name__}: {exc}"
        # Logged as well as returned. The status persists on the action
        # row, but the reason only rides back in the API response, and the
        # person debugging this at 2am is reading the server log.
        logger.warning("%s delivery failed: %s", channel, reason)
        return {"status": "failed", "error": reason}


async def generate(
    extracted: ExtractedFields,
    risk_level: str,
    risk_drivers: list[RiskDriver],
    patient_name: str,
    patient_phone: str | None,
    llm_client: LLMClientBase,
    whatsapp_client: WhatsAppClientBase,
    sms_client: SmsClientBase,
    phc_name: str = DEFAULT_PHC,
) -> list[dict]:
    actions: list[dict] = []
    now = datetime.now(timezone.utc)
    driver_text = "; ".join(f"{d.observation} -- {d.reason}" for d in risk_drivers)

    # FR-04.1: referral letter only for HIGH risk patients.
    if risk_level == "HIGH":
        referral_text = await _draft_referral_letter(llm_client, patient_name, extracted, phc_name, driver_text)
        actions.append({"type": "referral", "content": referral_text, "status": "draft"})

    # FR-04.2: WhatsApp summary draft in local language.
    #
    # Two texts, deliberately. `whatsapp_text` is the LLM's full, specific
    # message -- it names her actual readings and what to do -- and it is
    # what gets stored, shown in the dashboard and the app, and sent over
    # SMS, where nothing restricts the wording.
    #
    # What WhatsApp carries is an approved template. A follow-up reminder
    # is business-initiated: the patient has not messaged us, so there is
    # no open 24-hour customer service window and free-form text is
    # refused outright (131047). Sending the LLM text on that channel
    # would have failed for every real patient while passing every test
    # where we messaged the number first.
    whatsapp_text = await _draft_whatsapp_message(llm_client, patient_name, risk_level, driver_text)
    due_days = FOLLOWUP_DAYS.get(risk_level, 30)
    wa_result = await _attempt(
        lambda: _deliver_whatsapp(
            whatsapp_client, patient_phone or "", patient_name, risk_level, whatsapp_text, due_days
        ),
        "whatsapp",
    )
    actions.append({
        "type": "whatsapp",
        "content": whatsapp_text,
        "status": wa_result["status"],
        **({"error": wa_result["error"]} if "error" in wa_result else {}),
    })

    # SMS fallback (SRS section 11 risk register): a real delivery channel
    # for the same message when WhatsApp Business API isn't available yet.
    # Only fires when SMS_PROVIDER=real -- MockSmsClient means no SMS
    # credentials are configured, so nothing is added (mirrors how the
    # referral letter is skipped for non-HIGH risk: silent no-op, not an
    # empty/placeholder action).
    if not isinstance(sms_client, MockSmsClient):
        sms_result = await _attempt(
            lambda: sms_client.send_message(patient_phone or "", whatsapp_text), "sms"
        )
        actions.append({
            "type": "sms",
            "content": whatsapp_text,
            "status": sms_result["status"],
            **({"error": sms_result["error"]} if "error" in sms_result else {}),
        })

    # FR-04.3: follow-up task.
    due_at = now + timedelta(days=due_days)
    actions.append({
        "type": "followup",
        "content": f"Follow-up visit for {patient_name} ({risk_level} risk)",
        "status": "pending",
        "due_at": due_at.isoformat(),
    })

    return actions
