"""Agent 3 -- Action Generation (FR-04): referral letter, WhatsApp draft,
follow-up task with risk-based due date."""
import logging
from datetime import datetime, timedelta, timezone

from app.core.config import get_settings
from app.schemas.visit import ExtractedFields, RiskDriver
from app.services.llm_client import LLMClientBase, MockLLMClient
from app.services.sms_client import MockSmsClient, SmsClientBase
from app.services.whatsapp_client import WhatsAppClientBase

# FR-04.3: HIGH -> 48h, MEDIUM -> 7d, LOW -> 30d.
#
# UNASSESSED -> 1d, and it is not a risk tier. The visit produced no
# readable observation, so the outstanding work is redoing the visit, not
# waiting on a clinical interval. A month would be the LOW default and is
# the wrong answer for a patient nobody has actually assessed.
FOLLOWUP_DAYS = {"HIGH": 2, "MEDIUM": 7, "LOW": 30, "UNASSESSED": 1}
DEFAULT_PHC = "Primary Health Centre"

logger = logging.getLogger(__name__)

# FR-04.1: the referral letter's own scaffolding (labels, not clinical
# content), in the visit's spoken language.
#
# Hindi only, beyond the English default -- Hindi is both the pipeline's
# own default language_code and the SRS demo script's (section 9)
# language, so it is the one case where the deterministic/offline path
# (the one that actually runs during a judged demo -- see
# _draft_referral_letter's docstring) needs to visibly not be English.
# Kept to plain, unambiguous Hindi rather than guessed Marathi, Tamil,
# Telugu or Bengali labels nobody on this team can verify: these words
# sit on a document a real PHC doctor reads, and understandable beats
# guessed.
#
# ponytail: every language_code other than "hi" still falls back to
# English (see _referral_labels). Upgrade path: LLM_PROVIDER=real already
# asks the model to write the whole letter in the visit's language (see
# the prompt in _draft_referral_letter) -- the gap is only the four other
# languages on the offline/mock demo path, and closing it needs a
# reviewed translation, not one guessed here.
_REFERRAL_LABELS = {
    "en": {
        "title": "REFERRAL LETTER", "to": "To", "patient": "Patient", "age": "Age",
        "pregnancy_stage": "Pregnancy stage", "not_specified": "N/A",
        "reason": "Reason for referral", "high_risk": "HIGH risk",
        "prioritise": "Please prioritise clinical review at earliest opportunity.",
    },
    "hi": {
        "title": "रेफरल पत्र", "to": "प्रति", "patient": "मरीज़", "age": "आयु",
        "pregnancy_stage": "गर्भावस्था अवधि", "not_specified": "जानकारी नहीं",
        "reason": "रेफर करने का कारण", "high_risk": "उच्च जोखिम",
        "prioritise": "कृपया जल्द से जल्द जांच को प्राथमिकता दें।",
    },
}

# For the LLM path's prompt only -- telling the model which language to
# write in is safe (it does its own translation); guessing the words
# ourselves for languages nobody here reads is not (see above).
_LANGUAGE_NAMES = {
    "en": "English", "hi": "Hindi", "mr": "Marathi",
    "ta": "Tamil", "te": "Telugu", "bn": "Bengali",
}


def _referral_labels(language_code: str) -> dict:
    return _REFERRAL_LABELS.get(language_code, _REFERRAL_LABELS["en"])


def build_referral_letter(
    phc_name: str,
    patient_name: str,
    reason_text: str,
    language_code: str = "hi",
    age: int | None = None,
    pregnancy_stage: str | None = None,
    show_clinical_fields: bool = True,
) -> str:
    """The deterministic referral letter template -- one place, not two.

    Shared by the pipeline's auto-draft for a fresh HIGH visit
    (_draft_referral_letter, below) and the supervisor-override path that
    drafts one when an override moves a visit to HIGH after the fact
    (visits.override_risk), which used to hardcode its own copy of this
    exact template with DEFAULT_PHC baked in -- so an override letter was
    never localized and never went to the patient's actual PHC even after
    this file learned how to do both.

    `show_clinical_fields` is False for the override path: it has a
    reason (the supervisor's own) but not the structured `extracted`
    fields (age, pregnancy stage) the voice pipeline has, and printing
    "Age: N/A" on every override letter would look like missing data
    rather than a different call site.
    """
    labels = _referral_labels(language_code)
    lines = [labels["title"], "", f"{labels['to']}: {phc_name}"]
    patient_line = f"{labels['patient']}: {patient_name}"
    if show_clinical_fields:
        patient_line += f", {labels['age']} {age if age is not None else labels['not_specified']}"
        lines.append(patient_line)
        lines.append(f"{labels['pregnancy_stage']}: {pregnancy_stage or labels['not_specified']}")
    else:
        lines.append(patient_line)
    lines += [
        "",
        f"{labels['reason']} ({labels['high_risk']}): {reason_text}",
        "",
        labels["prioritise"],
        "-- Generated by SevakAI",
    ]
    return "\n".join(lines)


async def _draft_referral_letter(
    llm_client: LLMClientBase,
    patient_name: str,
    extracted: ExtractedFields,
    phc_name: str,
    driver_text: str,
    language_code: str = "hi",
) -> str:
    """FR-04.1. Deterministic template while LLM_PROVIDER=mock (the default
    -- keeps the demo pipeline offline and reproducible); real LLM-drafted
    prose, in the visit's own language, once LLM_PROVIDER=real. Branches
    on the client type rather than calling complete() unconditionally,
    because MockLLMClient's own generic placeholder text ("[mock LLM
    response for prompt beginning: ...]") is not something a user should
    ever actually see."""
    deterministic = build_referral_letter(
        phc_name, patient_name, driver_text, language_code,
        age=extracted.age, pregnancy_stage=extracted.pregnancy_stage,
    )
    if isinstance(llm_client, MockLLMClient):
        return deterministic
    language_name = _LANGUAGE_NAMES.get(language_code, language_code)
    try:
        body = await llm_client.complete(
            "You are drafting a formal referral letter from an ASHA (Accredited Social "
            "Health Activist) community health worker in India to a Primary Health Centre. "
            f"Write the letter in {language_name}. "
            "Write 4-6 concise, clinically appropriate sentences: identify the patient, "
            "state the specific reasons for referral drawn only from the observations "
            "given, and request prompt review. Do not invent facts not provided. Do not "
            "add a greeting, letterhead, or sign-off -- those are added separately.",
            f"Patient: {patient_name}, Age {extracted.age or 'unknown'}. "
            f"Pregnancy stage: {extracted.pregnancy_stage or 'not specified'}. "
            f"Referring PHC: {phc_name}. "
            f"Risk drivers: {driver_text}.",
        )
    except Exception as exc:  # noqa: BLE001 -- see _attempt: a drafting
        # failure must not lose the visit. Same fallback discipline as
        # extract_with_llm and classify_with_llm.
        logger.warning("referral drafting failed, using deterministic text: %s", exc)
        return deterministic
    labels = _referral_labels(language_code)
    return f"{labels['title']}\n\n{labels['to']}: {phc_name}\n\n{body.strip()}\n\n-- Generated by SevakAI"


async def _draft_whatsapp_message(
    llm_client: LLMClientBase,
    patient_name: str,
    risk_level: str,
    driver_text: str,
) -> str:
    """FR-04.2. Same mock/real split as the referral letter above."""
    deterministic = (
        f"Namaste {patient_name} ji, aapke ghar visit ke observations note kar liye gaye hain. "
        f"Risk status: {risk_level}. "
        + ("Kripya jaldi PHC visit karein." if risk_level == "HIGH" else "Apna follow-up visit na bhoolein.")
    )
    if isinstance(llm_client, MockLLMClient):
        return deterministic
    try:
        return await llm_client.complete(
            "You are an ASHA (Indian community health worker) drafting a short WhatsApp "
            "message in simple, warm Hindi (Devanagari script) to a patient after a home "
            "visit. Use respectful 'aap/ji' forms, avoid medical jargon, and keep it to "
            "2-3 short sentences: acknowledge the visit, mention what was observed in "
            "plain terms, and say what to do next.",
            f"Patient name: {patient_name}. Risk level: {risk_level}. "
            f"Observations: {driver_text or 'routine check, nothing concerning noted'}.",
        )
    except Exception as exc:  # noqa: BLE001 -- see above
        logger.warning("WhatsApp drafting failed, using deterministic text: %s", exc)
        return deterministic


# The three blanks the approved template declares, in her language rather
# than the API's. A patient should not be told her status is "HIGH".
_RISK_WORD = {
    "HIGH": "उच्च जोखिम",
    "MEDIUM": "मध्यम जोखिम",
    "LOW": "सामान्य",
}

_WHEN_WORD = {
    2: "दो दिन के अंदर",
    7: "एक हफ़्ते में",
    30: "एक महीने में",
}


async def _deliver_whatsapp(
    whatsapp_client: WhatsAppClientBase,
    patient_phone: str,
    patient_name: str,
    risk_level: str,
    drafted_text: str,
    due_days: int,
) -> dict:
    """Send the approved template, falling back to the drafted text on any
    provider that has no template concept.

    The fallback is not a workaround for an unapproved template -- it is
    for the mock and Twilio-sandbox providers, where free-form genuinely
    is the right call. On the meta path a refused template surfaces as a
    WhatsAppError with Meta's own reason rather than being papered over,
    because silently sending something else is how you find out at the
    demo that nothing was ever delivered.
    """
    settings = get_settings()
    try:
        return await whatsapp_client.send_template(
            patient_phone,
            settings.whatsapp_template_name,
            [
                patient_name,
                _RISK_WORD.get(risk_level, risk_level),
                _WHEN_WORD.get(due_days, f"{due_days} दिन में"),
            ],
            settings.whatsapp_template_language,
        )
    except NotImplementedError:
        return await whatsapp_client.send_message(patient_phone, drafted_text)


async def _attempt(send, channel: str) -> dict:
    """Run one delivery, turning any failure into a recorded outcome.

    Delivery must never be able to fail a visit. Agent 3 runs *after* the
    transcript, the extracted record and the risk classification already
    exist, and those are the things that matter clinically -- an expired
    WhatsApp token or a Twilio outage was taking the whole request down
    with it, so the ASHA saw no risk level at all for a visit the system
    had already assessed correctly.

    The failure is not swallowed: it lands on the action as status
    "failed" with the provider's own reason, so it is visible in the app
    and the dashboard and can be retried, rather than silently dropped.
    """
    try:
        result = await send()
        return {"status": result.get("status", "sent")}
    except Exception as exc:  # noqa: BLE001 -- deliberately broad; see above
        reason = f"{type(exc).__name__}: {exc}"
        # Logged as well as returned. The status persists on the action
        # row, but the reason only rides back in the API response, and the
        # person debugging this at 2am is reading the server log.
        logger.warning("%s delivery failed: %s", channel, reason)
        return {"status": "failed", "error": reason}


async def generate(
    extracted: ExtractedFields,
    risk_level: str,
    risk_drivers: list[RiskDriver],
    patient_name: str,
    patient_phone: str | None,
    llm_client: LLMClientBase,
    whatsapp_client: WhatsAppClientBase,
    sms_client: SmsClientBase,
    phc_name: str = DEFAULT_PHC,
    language_code: str = "hi",
) -> list[dict]:
    actions: list[dict] = []
    now = datetime.now(timezone.utc)
    driver_text = "; ".join(f"{d.observation} -- {d.reason}" for d in risk_drivers)

    # FR-04.1: referral letter only for HIGH risk patients.
    if risk_level == "HIGH":
        referral_text = await _draft_referral_letter(
            llm_client, patient_name, extracted, phc_name, driver_text, language_code
        )
        actions.append({"type": "referral", "content": referral_text, "status": "draft"})

    # FR-04.2: WhatsApp summary draft in local language.
    #
    # Two texts, deliberately. `whatsapp_text` is the LLM's full, specific
    # message -- it names her actual readings and what to do -- and it is
    # what gets stored, shown in the dashboard and the app, and sent over
    # SMS, where nothing restricts the wording.
    #
    # What WhatsApp carries is an approved template. A follow-up reminder
    # is business-initiated: the patient has not messaged us, so there is
    # no open 24-hour customer service window and free-form text is
    # refused outright (131047). Sending the LLM text on that channel
    # would have failed for every real patient while passing every test
    # where we messaged the number first.
    due_days = FOLLOWUP_DAYS.get(risk_level, 30)

    # Nothing goes to the patient for an unassessed visit. There is no
    # finding to tell her about, and "your risk status is unknown" is a
    # message that alarms without informing -- the problem is ours to fix,
    # not hers to act on. The follow-up task below is the whole response.
    if risk_level == "UNASSESSED":
        actions.append({
            "type": "followup",
            "content": (
                f"Re-record visit for {patient_name} -- nothing could be read from the "
                f"last recording"
            ),
            "status": "pending",
            "due_at": (now + timedelta(days=due_days)).isoformat(),
        })
        return actions

    whatsapp_text = await _draft_whatsapp_message(llm_client, patient_name, risk_level, driver_text)
    actions.append({
        "type": "whatsapp",
        "content": whatsapp_text,
        "status": "draft",
    })

    # SMS fallback (SRS section 11 risk register): a real delivery channel
    # for the same message when WhatsApp Business API isn't available yet.
    # Only fires when SMS_PROVIDER=real -- MockSmsClient means no SMS
    # credentials are configured, so nothing is added (mirrors how the
    # referral letter is skipped for non-HIGH risk: silent no-op, not an
    # empty/placeholder action).
    # Sending is deliberately separate: one ASHA-approved channel per action,
    # persisted in the outbox. Assessment never sends patient notifications.

    # FR-04.3: follow-up task.
    due_at = now + timedelta(days=due_days)
    actions.append({
        "type": "followup",
        "content": f"Follow-up visit for {patient_name} ({risk_level} risk)",
        "status": "pending",
        "due_at": due_at.isoformat(),
    })

    return actions
